### ISSUE TITLE
Transition issues on Gouketsuji Ichizoku (Japan) game

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/MegaDrive_MiSTer#11]
On the discord we discuss on transition during atrac mode of Gouketsuji Ichizoku game.
Dave'sGameRoom made a this video comparaison (left it is realHw, right it is core)

https://imgur.com/a/n2AL8Z2
We can see the RealHW keep white screen more longer and on the core we can see time to time garbage on the screen (like black dots) because the white screen is not keep.

Thanks

**Comment by MP2E** [comment]
This seems to happen even on the latest changes

**Comment by MP2E** [comment]
So I compared the intro of this game on the latest Nuked MS MiSter core vs my Genesis model 3 VA2 and I noticed the intro fade-out to white is exactly the same as my model 3.

This makes me think that the behavior currently is correct, it probably just depends on the revision of the console.

if someone could test this with a Model 1 VA7, that would prove whether this is the case or not

**Comment by birdybro** [comment]
The MD1 VA7 is the closest to the Nuked MD core, but it's still not going to be 1:1 because the combination of chips is not identical to any OG hardware. You should ask Dave to redo his recording with the latest build and make sure they are both accounting for things like duplicate frames from vsync, etc... Capture devices can be strange sometimes.

**Comment by wwark** [comment]
https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/469461/144cde3d-6148-4da6-acf7-8f708f454aa2
Dave made a new test and it is great now with the last unstable update.
Thank you Dave for your time and others for your tests

I will close this ticket !

**Comment by davedoc1984** [comment]
The Capture Device I use is set to match the Input it receives so it should be as close as I can get it.

The new Core version is now much closer to OG Hardware (my Japanese MD1 being a VA5 as I discovered yesterday).

I have posted a new capture from this morning (here in the UK) on Discord.
