### ISSUE TITLE
Virtua Racing (USA) Speedometer Graphics Corrupted

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/MegaDrive_MiSTer#18]
Latest unstable Build released today.

Speedometer Graphics are completely corrupted and do not look correct.

[https://cdn.discordapp.com/attachments/1096614378968727652/1152281866011938856/20230915_183531.jpg](url)

**Comment by davedoc1984** [comment]
Also affects the PAL / European version of the game. The Needle of the Speedometer is completely corrupted.

**Comment by birdybro** [comment]
[https://cdn.discordapp.com/attachments/1096614378968727652/1152281866011938856/20230915_183531.jpg](https://cdn.discordapp.com/attachments/1096614378968727652/1152281866011938856/20230915_183531.jpg)

Fixed your url.

**Comment by MP2E** [comment]
f3da5e606cc87ea7dee534c3b9754233ed99590c is the first bad commit, I found this by using git bisect and making builds + testing them

**Comment by birdybro** [comment]
That was done to fix this issue --> https://github.com/nukeykt/Nuked-MD-FPGA/issues/12

**Comment by MP2E** [comment]
Yes, it also fixed graphical glitches in James Bond 007: The Duel. So reverting is not the way to go, but I’m not sure how to properly fix this

**Comment by sorgelig** [comment]
I know why it happens. I'll look.

**Comment by davedoc1984** [comment]
Fixed with Today's Unstable release.
