### ISSUE TITLE
Single controller is sending wrong buttons and affecting 2P games

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/MegaDrive_MiSTer#2]
Tried with Streets of Rage using a single USB controller. Start playing normally then player 2 is suddenly added to the game play and single controller now controls both players with some wrong buttons mapped.

**Comment by MP2E** [comment]
I see this too, doesn’t matter whether the 6 button controller option is on or off

**Comment by MP2E** [comment]
Fixed, here's a build with the fix
[MegaDrive_20230901.zip](https://github.com/MiSTer-devel/MegaDrive_MiSTer/files/12498598/MegaDrive_20230901.zip)

**Comment by bootsector** [comment]
Thanks for looking at this, @MP2E
