### ISSUE TITLE
Analog video elevated blacks and green tint

### ISSUE THREAD

**Issue by leckel1996** [MiSTer-devel/MegaDrive_MiSTer#28]
Using analog out there is a green tint and the black levels are elevated compared to the hdmi output.

**Comment by birdybro** [comment]
What kind of connection are you using for analog?

**Comment by leckel1996** [comment]
VGA output to RGBHV cable and using RGBS output from the mister. Every other core I’ve tested looks correct as far as black levels and color.

**Comment by birdybro** [comment]
Hrmm maybe the core is sending out some green instead of black during vblank...

**Comment by sorgelig** [comment]
strange that no other users complained yet. May be it's something specific between particular TV and this core

**Comment by leckel1996** [comment]
I will say I’m probably not the typical user as far as my background and what I do for my job. 
![IMG_3221](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/107373366/5badae6b-1b12-4313-94e0-da497403ccec)
![IMG_3220](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/107373366/2c61ec83-6197-40b5-80a1-d377c95af9c1)

Here are some not so great pictures of the 240p test suite on the genesis core and nuked md core.

**Comment by birdybro** [comment]
What Make/Model of CRT is it? I agree it's probably something that only affects certain CRT's. The TMNT arcade core had a tangentially similar issue early on that was related to specific different CRT's.

**Comment by leckel1996** [comment]
JVC BM-H1900SU

**Comment by MP2E** [comment]
Strange, looks ok on my Sony PVM-1953MD. Though I’m also using direct video
![APC_0055](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/167708/4728ef30-806c-4e70-9ec7-d7411f94ab17)

**Comment by leckel1996** [comment]
HDMI output looks fine so I wouldn’t expect direct video to have the same issue

**Comment by leckel1996** [comment]
I’m going to get a vga cable and connect the output to my ossc to see if I see the same thing.

**Comment by birdybro** [comment]
Have you already tried changing the outcome by changing these options in your MiSTer.ini?

https://github.com/MiSTer-devel/Main_MiSTer/blob/master/MiSTer.ini#L5-L6
https://github.com/MiSTer-devel/Main_MiSTer/blob/master/MiSTer.ini#L33

**Comment by leckel1996** [comment]
The sync on green switch on the analog io board seemed to fix it. For whatever reason its effect was a lot more drastic with this core than the other cores. Thanks for solving my problem even though it had nothing to do with the core.

**Comment by birdybro** [comment]
Sweet!
