### ISSUE TITLE
Sonic 2 - 2 Player mode displays slightly incorrectly (480i)

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/MegaDrive_MiSTer#30]
In 2 player mode, if you look closely at the text, it seems to be slightly off. I'm not sure how to describe this particular issue. This is with a CRT connected via direct video. I compared side by side with a real megadrive and the text looked clear there

**Comment by sorgelig** [comment]
Interlace mode is off on VGA/DirectVideo. 
I don't have CRT to fix it. I have scaler but not sure if i can test interlace with that.
