### ISSUE TITLE
X-men Problem

### ISSUE THREAD

**Issue by bonovox2k** [MiSTer-devel/MegaDrive_MiSTer#35]
This game needs in the 7 Stage Mojo Worlds after defeat the MOJO boss you need to press RESET on the cosole to play last stage and you can face MAGNETO.. in old mister core works perfectly but in the NUKED the game simple reset to the begining make impossible to finish the game.

**Comment by Death-Devil-94** [comment]
I can confirmed too, reset function is actually Hard Reset in Nuked core. In X-Men stage 7, need to defeat the boss and plus destroying computer, then hit RESET button to continue the game

**Comment by sorgelig** [comment]
is there a test rom where i can debug such reset function?

**Comment by Death-Devil-94** [comment]
> is there a test rom where i can debug such reset function?

tested with enable cheats on original ROM: infinite health, stage select at the beginning 

idk if there is allowed to upload ROM

**Comment by sorgelig** [comment]
ok. i will try

**Comment by sorgelig** [comment]
on which place i need to press reset? 
Is it that room after destroying some panel/screen?

**Comment by bonovox2k** [comment]
Yes after destroy The panel Just press reset

Em sex., 27 de out. de 2023 13:06, Alexey Melnikov ***@***.***>
escreveu:

**Comment by odiaboeeu** [comment]
I believe this will help.

https://github.com/MiSTer-devel/Genesis_MiSTer/pull/128

**Comment by sorgelig** [comment]
i've pushed the fix

**Comment by bonovox2k** [comment]
Awesome, thanks!

Em sex., 27 de out. de 2023 17:46, Alexey Melnikov ***@***.***>
escreveu:

**Comment by bonovox2k** [comment]
MegaDrive_unstable_20231027_20d3f9 this version fix the RESET BUG ! Thanks a lot Mr Sorgelig ! ;-)
