### ISSUE TITLE
Jagged characters in Ys 3 (Japan)

### ISSUE THREAD

**Issue by farsil** [MiSTer-devel/MegaDrive_MiSTer#37]
Hello,

I have noticed that, compared to the Genesis core, the characters from the Japanese version of the game look jagged while they walk, as if there was some interlacing issue:

![PXL_20231118_140100435 MP](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/18445221/69dcb064-bc1c-44a5-b2b4-fd88bac2febf)

What could cause that? Is it a setting on my core or is it a bug in the emulation?

I can provide the ROM hash if necessary.

Thank you!

**Comment by sorgelig** [comment]
It's not a problem with core. There 2 different VDP versions. 
From my memory: Japanese VDP had bug which was workarounded in this game but at the same time on non-japanese MD it has problem. So basically Japanese Ys 3 is fine on Japanese MD, and English Ys 3 is ok on non-Japanese MD.

Only this game is affected.
Genesis core adds that bug for only this game to make it work. Nuked-MD core is hard to modify.

**Comment by sorgelig** [comment]
Are you sure it's ok or real HW?

**Comment by farsil** [comment]
I don't own a MD to test this unfortunately. My frame of reference is the Genesis core which didn't show this artifacting.

**Comment by sorgelig** [comment]
> I can't see your other message in this thread, but it was delivered by email.

because i messed with Ys on SMS :) It had different problem with broken panel on bottom. 
So jagged look is completely different thing.

**Comment by birdybro** [comment]
I can't reproduce this in the core. I suspect it's something to do with your display device.

https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/16388068/94535b21-5cba-4bab-a5df-e0518ae428ac

**Comment by farsil** [comment]
I tried on a new save file and I cannot reproduce it either. It may have something to do with my current save, which is imported from the Genesis core. I thought the two save file formats were identical, but maybe there are subtle differences?

At any rate, I'll close this for now, thank you for taking the time to address this GitHub issue.
