### ISSUE TITLE
Feature Request: Analogue Pocket Support

### ISSUE THREAD

**Issue by ijwrighty1** [MiSTer-devel/MegaDrive_MiSTer#38]
Fantastic core, congratulations. Plays a lot of my favourite games more accurately than the other version.

Is it possible to get this working for the Analogue Pocket?

**Comment by sorgelig** [comment]
This is MiSTer repository. You have to ask people from Analogue.

**Comment by ijwrighty1** [comment]
Is that the official analogue team or is there a repo somewhere?

**Comment by sorgelig** [comment]
No idea
