### ISSUE TITLE
EXT port support

### ISSUE THREAD

**Issue by viciious** [MiSTer-devel/MegaDrive_MiSTer#4]
This is basically a repost of the following issue for the other Genesis core: https://github.com/MiSTer-devel/Genesis_MiSTer/issues/233

Initial revisions of MegaDrive Model 1 had the so-called EXT port at the back, which was mostly intended to be used with Sega Modem. But for the most part, it's just a third controller port, gender reversed. It would be nice if the MiSTer's MD core offered support for it to allow for some interesting things for homebrew games. After all, it's canon hardware, albeit not present in all revisions.

More info here:

https://plutiedev.com/io-ports

https://github.com/ares-emulator/ares/blob/master/ares/md/cpu/io.cpp#L23

https://github.com/ares-emulator/ares/blob/master/ares/md/controller/port.hpp#L68

**Comment by sorgelig** [comment]
It's already supporting. Choose SNAC: port 3.

**Comment by viciious** [comment]
Oh, I assumed it would be mapped to the USER port on MiSTer. I guess port 3 on SNAC is also fine, sorry for the false alarm :)

**Comment by sorgelig** [comment]
USER port = SNAC.
Just different names.
