### ISSUE TITLE
Crash in Mortal Kombat: Revelations (Hack for Sega Genesis)

### ISSUE THREAD

**Issue by TpaBkaY** [MiSTer-devel/MegaDrive_MiSTer#43]
When the fight starts, after some time the next crash occurs: 
![photo_2024-05-21_20-35-09](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/169945586/b851d6a6-5638-4a74-813d-e581b16f9699)

The full name of rom: _Mortal_Kombat_Revelations_v1.0_hack_by_Smoke.bin_ or _Mortal Kombat Revelations (Ultimate Mortal Kombat 3 modification) (1.0).md_

**Comment by birdybro** [comment]
https://www.romhacking.net/reviews/1437/#review

This is an older romhack that apparently is known to be buggy. How does it behave on original hardware?
