### ISSUE TITLE
San Guo Yan Yi: Huo Shao Chi Bi stuck in infinite loop

### ISSUE THREAD

**Issue by Jacky412** [MiSTer-devel/MegaDrive_MiSTer#46]
Hi I am on the latest megadrive core and the game "San Guo Yan Yi: Huo Shao Chi Bi" is not working correctly. It will load into the start menu but as soon as you press start it will stuck in an infinite loop looping the intro over and over and again.

This game works perfectly on real cartridge on real megadrive console.

This is a video of it working correctly on real megadrive console:

https://www.youtube.com/watch?v=PLc_-34K_0Y

**Comment by sorgelig** [comment]
I think it's unlicensed game. They usually have protection chip. It has nothing to do with core itself, just such chip is not emulated. Usually there is a patch for such dump of cartridge removing the protection.

**Comment by birdybro** [comment]
It's an unofficial port of this game - https://segaretro.org/Tenchi_wo_Kurau_II:_Sekiheki_no_Tatakai - so you could at least experience what the original game is on MiSTer as well in the Saturn core for now :)

**Comment by Jacky412** [comment]
Thank you. If that is the case I shall close this issue then.
