### ISSUE TITLE
Space Harrier 2 glitches

### ISSUE THREAD

**Issue by Toryalai1** [MiSTer-devel/MegaDrive_MiSTer#7]
Space Harrier 2 shows many glitches when launching the core for the first time. When resetting the console through OSD, the glitching disappears. ![image](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/82502378/8a7f2608-d684-47ab-b0cf-ab7ac0e67e64)![image](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/82502378/30488b5e-4071-46cc-9457-b811642e108d)![image](https://github.com/MiSTer-devel/MegaDrive_MiSTer/assets/82502378/b6ef61a6-5594-41f1-800e-63180fc1312a)

**Comment by Toryalai1** [comment]
Seems to be fixed here:
https://github.com/nukeykt/Nuked-MD-FPGA/commit/51db4d515a41e466e4cd3c6128fad2a8ef9af177

**Comment by MP2E** [comment]
[MegaDrive_20230904.zip](https://github.com/MiSTer-devel/MegaDrive_MiSTer/files/12511920/MegaDrive_20230904.zip)
Here's a build with nukey's latest changes to Nuked MD
