### ISSUE TITLE
Cannot launch games using <setname> in mgl

### ISSUE THREAD

**Issue by RGarciaLago** [MiSTer-devel/MegaDrive_MiSTer#8]
Using an mgl file to launch games presents no issues; core then game are launched as expected. However, when utilizing `<setname>` within an mgl, it only launches the core and not the game. Changing the value of  delay or index does not resolve the issue.

Below is an example of an mgl with a `<setname>` set with this core:
```
<mistergamedescription>
	<rbf>_Console/MegaDrive</rbf>
	<setname>MegaDrive_LightGun</setname>
	<file delay="1" type="f" index="0" path="../../../../media/fat/games/MegaDrive/Light-gun/Body Count.md"/>
</mistergamedescription>
```

**Comment by sorgelig** [comment]
must be `index="1"`

**Comment by RGarciaLago** [comment]
Unfortunately setting `index="1"` doesn't resolve the issue. Although incorrect, having index=0 works fine for launching games through mgl.

**Comment by sorgelig** [comment]
It works:
1) you have to use `index="1"` for MD roms
2) Folder for new setname should exist, otherwise relative path will fail.

**Comment by sorgelig** [comment]
i've added support for absolute paths in MGL. Should be available in unstable build of Main.
